[workspace]

members = ["day_one", "day_three", "day_two"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.3"
anyhow = "1.0.93"
